### ISSUE TITLE
Extension does not load in forge

### ISSUE THREAD

**Issue by Gushousekai195** [MAPS-research/sd-webui-ditail#6]
After installing this extension through the Extensions tab in Forge, upon restarting I get:

```
*** Error loading script: ditail_ext.py
    Traceback (most recent call last):
      File "D:\AI\webui_forge_cu121_torch21\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\webui_forge_cu121_torch21\webui\extensions\sd-webui-ditail\scripts\ditail_ext.py", line 20, in <module>
        from ditail.extract_features import ExtractLatent
      File "D:\AI\webui_forge_cu121_torch21\webui\extensions\sd-webui-ditail\ditail\extract_features.py", line 10, in <module>
        from ldm.models.diffusion.ddim import DDIMSampler
    ModuleNotFoundError: No module named 'ldm'
```

**Comment by RicercarG** [comment]
Hi @Gushousekai195, thanks for raising this issue.

Illyasviel’s stable-diffusion-webui-forge has a slightly different backend compared to A1111’s webui, and we haven’t implemented support for it yet. 

We recommend using this extension exclusively with A1111’s webui for the time being. However, we are actively working towards supporting webui-forge in the future.
